spring:
  datasource:  # 配置mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb1:3306/dev
    username: root
    password: hasaiki
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
server:
  port: 8080  # 默认端口
